### ISSUE TITLE
Error: Warning not odt when using with Libreoffice 6.2.2.2 .odt files

### ISSUE THREAD

**Issue by menelic** [kappapiana/script#1]
This script is great, much needed for academic review  - unfortunately I cannot get it to work, it claims myLibeOffice 6.2.2.2  odt files are not odt files...I even tied to delete the script lines that do the file check, but that did not work either - please assist, I am sure many text workers would appreciate!

**Comment by kappapiana** [comment]
Hi, sorry for not replying earlier, I didn't expect any feedback and github doesn't warn me of new issues (my faul). I could not replicate the error. Would you try with the new version of the script (also working with docx)?
