### ISSUE TITLE
Script runs, but name is unchanged

### ISSUE THREAD

**Issue by TepoltC** [kappapiana/script#2]
Just tried this, and the script ran and correctly identified the name to be stripped from the file with no obvious errors. However, the original name remained in the "anonymized" document comments. I had saved the original .docx file as .odt, and ran the script on the .odt. Not sure if that caused the issue?

Anyway, wanted to report it since this would be a terrific function to have if I could get it to work! Thanks for sharing it.

**Comment by kappapiana** [comment]
Would you try again with the new script? (sorry for not replying earlier, I didn't really expect anybody to notice) 

For the time being you must run the script from the same directory as the document. The file name remains unchanged in case you are unhappy of the result, so you have the original and the anonimyzed version side by side.

**Comment by kappapiana** [comment]
@tepolt I have written a new script in Python. Perhaps you will want to try it? Its in a different repo now: https://github.com/kappapiana/anonymize

I would love to receive feedback.
