### ISSUE TITLE
question about functionality

### ISSUE THREAD

**Issue by jlovejoy** [kappapiana/script#3]
does this work for making track changes and comments anonymized - so it looks like they all were from one person, instead of a rainbow of colored changes? 
If I have that right, I'd like to help update your documentation to be a bit more newbie-Linux-user friendly (like myself).  :)

**Comment by kappapiana** [comment]
Hi, this stupid thing doesn't warn me of comments, so I've not replied. It is correct. 

I didn't expect anybody to notice and therefore I've not checked until now. I have completely overhauled the thing and now it works with docx too... :-) 

If you want to test it...
